### ISSUE TITLE
How to export sub-headlines?

### ISSUE THREAD

**Issue by Ypot** [eyeinsky/org-anki#46]
Hi
I love your idea, it is perfect to study org-mode notes and it works with no problems. Thanks

How could I export a collection of exams?  
I have added this to my .init file, but it doesn't seem to work:

```
(customize-set-variable 'org-anki-default-match "tree")
(customize-set-variable 'org-anki-match "tree")
```

* Exams
** Question 1
    Answer 1
** Question 2
    Answer 2
** ...
    ...

**Comment by eyeinsky** [comment]
It may be easier to copy the questions to a temporary buffer, set it to org-mode and run `org-anki-sync-all` (with no restrictions) there.

Otherwise the code below works. Note that `'tree` is the `SCOPE` argument to`org-map-entries`, while `MATCH` is set to `nil`  
```elisp
(org-anki--sync-notes
   (org-map-entries 'org-anki--note-at-point nil 'tree))
```

(Note also that `org-anki-match` is a constant that can't (and shouldn't) be set. It points to the name of the property from the value of which the match argument is taken.)
